### ISSUE TITLE
Issue with installing 

### ISSUE THREAD

**Issue by kh-kr** [nmdickson/GCfit#177]
Hi, 

I would like to install GCfit. I tried it using the following command given on the github
"_pip install git+ssh://git@github.co^Cnmdickson/GCfit.git_"

but it is throwing the following error msg:
'''
 git@github.com: Permission denied (publickey).
  fatal: Could not read from remote repository.

  Please make sure you have the correct access rights
  and the repository exists.
WARNING: Discarding git+ssh://****@github.com/nmdickson/GCfit.git. Command errored out with exit status 128: git clone -q 'ssh://****@github.com/nmdickson/GCfit.git' /tmp/pip-req-build-7jvn3gdz Check the logs for full command output.
ERROR: Command errored out with exit status 128: git clone -q 'ssh://****@github.com/nmdickson/GCfit.git' /tmp/pip-req-build-7jvn3gdz Check the logs for full command output.
'''

Any help regarding solving this issue would be highly appreciated.

Thank you!

**Comment by nmdickson** [comment]
Hi there,
This is a permissions issue (and an oversight in the docs).
Give it a try using https instead:

`pip install git+https://github.com/nmdickson/GCfit.git`

Hope that works for you
