### ISSUE TITLE
Change which milky way potential is used in `galactic_component` to simplify installation

### ISSUE THREAD

**Issue by nmdickson** [nmdickson/GCfit#46]
Currently in computing the galactic component of pulsar acceleration we use the `BovyMWPotential2014` galactic potential class, from `gala`. This is based off of the Bovy (2015) paper which fit the parameters of a 3-component potential to various data, and seems to be considered a sort of "standard".
The issue is that, in `gala`, this class requires the package to have been installed with GSL support.
In practice this dependency has turned out to be, by far, the most annoying, and I can't always even be certain why. It makes it so `gala` often has to be installed separately from other dependencies, or given special consideration. In fact, the most recent version of `gala` (1.4.1) seems to be even more troublesome in this regard, and I can't get it to compile with GSL at all, despite going through it's setup scripts and ensuring everything is in the right place on our end. I had to ensure that `gala==1.3` was installed, and requiring an old package version is not a sustainable practice.

All that said, while this potential seems to be the best, there is another `MilkyWayPotential` in `gala` (also from Bovy, 2015) which does not require GSL.
From Bovy (2015): 

> Finally, note that galpy contains an older version of a similar potential: MWPotential. This model was not fit to data on the Milky Way (although it is close to a good model) and is now superseded by MWPotential2014.

The question I'm posing here is whether the change/benefit of the newest potential is enough to justify the trouble caused by the installation woes. I weigh scientific accuracy much much higher than "installation woes", but this potential is used in a single, small, obscure part of the package, and only affects the pulsars. I think it is at least worth examining the differences between the two potentials, and deciding which we want to go with.

**Comment by pjs902** [comment]
Switched to `MilkyWayPotential2022` in #214.
